# -*- coding: utf-8 -*-
"""BDA Lab Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTC9vhChnJz0_hc0PcBakhACSLNLTr4U
"""



# to=============================
# IMPORT LIBRARIES
# =============================from pyspark.sql import SparkSession
import numpy as np
import pandas as pd
import pyspark.sql.functions as F
from pyspark.sql.functions import *
from pyspark.sql.types import StringType
from datetime import datetime
import time
import matplotlib.pyplot as plt
from pyspark.sql import SparkSession

# =============================
# CREATE SPARK SESSION
# =============================
spark = SparkSession.builder.appName("capstone").getOrCreate()

# =============================
# LOAD DATA
# =============================
def load_data(data):
    t1 = time.time()
    df = spark.read.options(header=True, inferSchema=True).csv(data)
    t2 = time.time()
    print("Duration:", np.round((t2 - t1), 2), "seconds")
    return df

df1 = load_data("OnlineRetail.csv")

def datashape(data):
    print("Data shape (rows, columns):", data.count(), "x", len(data.columns))
datashape(df1)
df1.limit(5).show()

# =============================
# SUMMARY STATISTICS
# =============================
spark.conf.set("spark.sql.repl.eagerEval.enabled", True)

summary = df1.describe().toPandas()
summary = summary.T
summary.columns = summary.iloc[0]
summary = summary.drop(summary.index[0])
summary

import matplotlib.pyplot as plt
import pandas as pd

# Create a copy to avoid modifying the original summary DataFrame
summary_to_plot = summary.copy()

# Convert 'count' column to numeric, coercing errors to NaN
summary_to_plot['count'] = pd.to_numeric(summary_to_plot['count'], errors='coerce')

# Drop rows where 'count' is NaN after conversion (these were likely non-numeric original values)
summary_to_plot = summary_to_plot.dropna(subset=['count'])

# Plotting the count for each feature
plt.figure(figsize=(10, 6))
plt.bar(summary_to_plot.index, summary_to_plot['count'])
plt.xlabel("Features")
plt.ylabel("Count of Non-Null Values")
plt.title("Count of Non-Null Values for Each Feature (from summary)")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# =============================
# MISSING VALUES CHECK
# =============================

# Dynamically create missing value conditions based on column type
missing_conditions = []
for c, dtype in df1.dtypes:
    # Start with a check for null values for all columns
    condition = col(c).isNull()

    # Add isnan() check only for numeric types
    if dtype.startswith("double") or dtype.startswith("float") or dtype.startswith("int") or dtype.startswith("long"):
        condition = condition | isnan(c)

    missing_conditions.append(count(when(condition, c)).alias(c))

# Select the counts of missing values based on the constructed conditions
missing = df1.select(missing_conditions)
missing.show()

# =============================
# DATA CLEANING
# =============================

# Fix Country name
df1 = df1.replace(['EIRE'], ['Ireland'])

# Convert Quantity to float
df1 = df1.withColumn("Quantity", col("Quantity").cast("Float"))

# =============================
# CREATE AMOUNT COLUMN
# =============================
df1 = df1.withColumn("Amount", col("Quantity") * col("UnitPrice"))
df1.limit(5).show()

# =============================
# TOP 10 COUNTRIES BY TRANSACTIONS
# =============================
df1.groupBy("Country").count().sort(col("count").desc()).limit(10).show()

# =============================
# FILTER IRELAND DATA
# =============================
df1.filter(df1.Country == "Ireland").limit(5).show()

# =============================
# FILTER LARGE QUANTITY SALES
# =============================
df1.filter(df1.Quantity > 50000).show()

# =============================
# DAILY TRANSACTION COUNT
# =============================
daily_txn = df1.groupBy("InvoiceDate").count().sort("InvoiceDate", ascending=True)
daily_txn.show(10)

# =============================
# FINAL RESULT CHART
# =============================

# Convert to pandas
daily_pd = daily_txn.toPandas()

# Convert date column (if needed)
daily_pd["InvoiceDate"] = pd.to_datetime(daily_pd["InvoiceDate"])

# Plot chart
plt.figure(figsize=(12, 5))
plt.plot(daily_pd["InvoiceDate"], daily_pd["count"])
plt.xlabel("Date")
plt.ylabel("Number of Transactions")
plt.title("Daily Transactions Over Time")
plt.xticks(rotation=45)
plt.show()

# =============================
# PIE CHART FOR TOP COUNTRIES
# =============================

# Group by Country and count transactions
country_counts = df1.groupBy("Country").count()

# Sort and get top 5 countries
top_5_countries = country_counts.sort(col("count").desc()).limit(5).toPandas()

# Calculate count for 'Other' countries
other_count = country_counts.filter(~col("Country").isin(top_5_countries["Country"].tolist()))\
                               .agg(F.sum("count").alias("count")).collect()[0]["count"]

# Add 'Other' category to the DataFrame
if other_count is None: # Handle case where there are less than 5 countries
    other_count = 0
other_df = pd.DataFrame([{"Country": "Other", "count": other_count}])
final_country_data = pd.concat([top_5_countries, other_df])

# Plotting the pie chart with improved spacing
plt.figure(figsize=(10, 8))
plt.pie(final_country_data['count'],
        labels=final_country_data['Country'],
        autopct='%1.1f%%',
        startangle=140,
        pctdistance=0.85, # Distance of percentage labels from the center
        wedgeprops=dict(width=0.4, edgecolor='w')) # Adds space between slices and a white edge
plt.title("Transaction Distribution by Country (Top 5 + Other)")
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

# =============================
# MONTHLY TRANSACTION COUNT
# =============================
# Extract YearMonth from InvoiceDate for monthly aggregation
df_monthly = df1.withColumn("InvoiceMonth", date_format(to_timestamp(col("InvoiceDate"), "M/d/yyyy H:mm"), "yyyy-MM"))

monthly_txn = df_monthly.groupBy("InvoiceMonth").count().sort("InvoiceMonth", ascending=True)
monthly_txn.show(10)

# =============================
# MONTHLY TRANSACTION CHART
# =============================

# Convert to pandas
monthly_pd = monthly_txn.toPandas()

# Convert date column
monthly_pd["InvoiceMonth"] = pd.to_datetime(monthly_pd["InvoiceMonth"])

# Plot chart
plt.figure(figsize=(12, 5))
plt.plot(monthly_pd["InvoiceMonth"], monthly_pd["count"])
plt.xlabel("Month")
plt.ylabel("Number of Transactions")
plt.title("Monthly Transactions Over Time")
plt.xticks(rotation=45)
plt.show()

